version: 2
locations:
  docs:
    from: /home/cell/Documents
    to: b2bucket
    forget: prune
    options:
      forget:
        keep-last: 7


backends:
  b2bucket:
    type: b2
    path: charithe:backup/Documents
